language: java
jdk:
  - oraclejdk8

before_install:
 - chmod +x gradlew

install:
  - cd /tmp; git clone https://github.com/coinblesk/coinblesk-shared-resources.git; cd coinblesk-shared-resources; 
  - ./gradlew clean test
  - ./gradlew clean install
  - gradle --version
  
script:
  - ./gradlew clean test