language: java
jdk:
  - oraclejdk8
install:
  - cd /tmp; git clone https://github.com/coinblesk/coinblesk-shared-resources.git
  - cd coinblesk-shared-resources; gradle clean install
  
script:
  - gradle clean test -i